name: Build Web Assets
description: 'Builds the web assets and publishes the output'

inputs:
  dotnet-version:
    description: 'The version of the .Net Core SDK to use'
    required: true
  project-pattern:
    description: 'The pattern to use to find the test projects'
    required: true
  solution-name:
    description: 'The name of the solution'
    required: true
    
runs:
  using: "composite"
  steps:

    - name: 'Set Dotnet Version ${{ inputs.dotnet-version }}'
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Install Dependencies
      shell: bash
      run: dotnet restore ${{ inputs.solution-name }}

    - name: Build Solution
      shell: bash
      run: dotnet build ${{ inputs.project-pattern }} --configuration Release --no-restore

    - name: Publish Web Assets
      shell: bash
      run:  |
        dotnet publish --property:PublishDir="${{ github.workspace }}/output" ${{ inputs.project-pattern }}

    - name: Publish Web Assets Artifact
      uses: actions/upload-artifact@v4
      with:
        name: test_WebAssets
        path: ${{ github.workspace }}/output/wwwroot
        # retention-days: 1